### ISSUE TITLE
Ask a quiestion/request a service

### ISSUE THREAD

**Issue by acq1001** [acq1001/practica2_gespro#19]

**Comment by rls1004ubu** [comment]
¿Hay límite de preguntas o servicios? es decir, ¿se puede realizar las preguntas o solicitar los servicios que se deseen?

**Comment by acq1001** [comment]
Claro que no, cualquier usuario podra realizar tantas preguntas como precise.
Respecto a los servicios, por el momento, cada usuario podra solicitar tan solo tres servicios.

**Comment by roberLastras** [comment]
En un futuro, ¿será posible solicitar más de tres servicios?
