### ISSUE TITLE
Manage the app from an Android device

### ISSUE THREAD

**Issue by acq1001** [acq1001/practica2_gespro#22]

**Comment by rls1004ubu** [comment]
¿Qué versiones de Android están disponibles?

**Comment by acq1001** [comment]
A partir de la version 4.1, que coincide con la primera version compatible con whatsapp

**Comment by roberLastras** [comment]
¿Hay alguna diferencia entre administrar la aplicación desde un dispositivo Android o administrarla desde un dispositivo iPhone?
