### ISSUE TITLE
Customize notifications

### ISSUE THREAD

**Issue by acq1001** [acq1001/practica2_gespro#37]

**Comment by rls1004ubu** [comment]
¿Se pueden silenciar las notificaciones?

**Comment by acq1001** [comment]
Si, desde el menú de ajustes se podran deshabilitar o habilitar las notificaciones

**Comment by roberLastras** [comment]
Vale, muchas gracias, a parte de eso, ¿es posible habilitar solo las notificaciones que me interesen?
