### ISSUE TITLE
Calculate deposit options

### ISSUE THREAD

**Issue by acq1001** [acq1001/practica2_gespro#41]

**Comment by acq1001** [comment]
¿PayPal estará aceptado como forma de depósito o pago? ¿En caso de dispositivos Android, se podrá realizar micro pagos con el saldo de Google Play?

**Comment by roberLastras** [comment]
Sí, se podrá pagar con PayPal o con tarjeta de crédito/débito y también se podrá realizar micro pagos desde Google Play.
